export const PRACTICE_TEXTS: string[] = [
  "Practice makes progress, not perfection.",
  "Typing quickly is useful, but typing accurately is powerful.",
  "Small improvements every day add up to big results over time.",
  "Focus on smooth rhythm before pushing for maximum speed.",
  "Accuracy first, then speed will naturally follow.",
  "Consistent practice turns a weakness into a strength.",
  "Clear hands, calm mind, and eyes on the text.",
  "Speed without control leads to careless mistakes.",
  "Stay relaxed; tension only slows your fingers down.",
  "Every correct keystroke builds your confidence.",
  "Short bursts of focused practice beat long distracted sessions.",
  "Your typing skills grow one sentence at a time.",
  "The keyboard becomes easier as your muscle memory improves.",
  "Look at the screen, not at your hands.",
  "Trust your fingers to remember the keys they have learned.",
  "Typing is a language between your brain and your keyboard.",
  "Measure progress in weeks and months, not minutes.",
  "Your future self will thank you for today's practice.",
  "Errors are feedback, not failure.",
  "Slow down slightly to avoid a flood of typos.",
  "Accuracy above ninety five percent is a solid target.",
  "Warm up with shorter sentences before long passages.",
  "Even expert typists sometimes need to reset and refocus.",
  "Breathing steadily helps maintain a smooth typing pace.",
  "Good posture protects your wrists during long sessions.",
  "Light touches on the keys reduce strain and increase speed.",
  "Keep your fingers close to the home row at all times.",
  "Quick correction of typos prevents confusion later.",
  "Reading the entire sentence once can reduce mistakes.",
  "Do not rush the first five seconds of each attempt.",
  "Tracking your words per minute can be very motivating.",
  "Aim for both speed and clarity when you type.",
  "Typing is a core skill for modern work and study.",
  "The best way to improve is to keep showing up.",
  "You can always shave a few seconds off your best time.",
  "Stay patient; mastery is built through repetition.",
  "Challenge yourself with tricky punctuation and numbers.",
  "Switching passages regularly keeps practice interesting.",
  "Typing common phrases builds natural fluency.",
  "Confidence grows as you reduce your error rate.",
  "Practice now so stressful exams feel easier later.",
  "Typing games can make learning fun and engaging.",
  "Try to type this sentence without a single mistake.",
  "Accuracy plus speed equals true typing mastery.",
  "Occasional breaks keep your focus sharp and fresh.",
  "Your hands are learning a precise new dance.",
  "Typing well saves hours across a lifetime of work.",
  "You are teaching your fingers a very useful habit.",
  "Stay curious and keep testing your limits.",
  "When you feel tired, switch to slower accuracy drills.",
  "High accuracy means you rarely need to press backspace.",
  "Celebrate small personal records as real achievements.",
  "A calm tempo is faster than frantic rushing.",
  "Keep your wrists level with the keyboard if you can.",
  "Good lighting reduces eye strain while you type.",
  "Typing fast is satisfying, like playing an instrument.",
  "Your first attempts will be rough, and that is okay.",
  "Learn from each typo and adjust your hand position.",
  "Trust the process and keep practicing regularly.",
  "Set a goal for words per minute and aim for it.",
  "Your best scores will come when you are focused.",
  "Do not chase numbers at the expense of technique.",
  "Stretch your fingers gently between long sessions.",
  "Typing tests are easier when you feel prepared.",
  "Mix easy and challenging passages for variety.",
  "Train both short bursts and longer endurance runs.",
  "Accuracy is your foundation for high speed.",
  "Type this sentence smoothly, not just quickly.",
  "Double check punctuation marks like commas and periods.",
  "Practice with numbers to strengthen your right hand.",
  "Typing can feel like a game when you track progress.",
  "Every mistake is a chance to refine your skills.",
  "You are faster today than you were last week.",
  "Stay relaxed in your shoulders and neck.",
  "Tilt the keyboard only if it feels comfortable.",
  "Lower error rates will naturally raise your speed.",
  "Do not compare your progress to other people.",
  "The only fair comparison is with your past self.",
  "Tight deadlines feel easier with strong typing skills.",
  "Practicing now will save you precious time later.",
  "Repetition turns awareness into automatic habit.",
  "Even a few minutes of focused work can help.",
  "Monitoring accuracy keeps sloppy habits away.",
  "Use all ten fingers for the best long term gains.",
  "The spacebar is pressed most often with one thumb.",
  "Keep your elbows close and your back straight.",
  "A comfortable chair can improve your focus.",
  "Do not forget to blink and rest your eyes.",
  "Practice with unfamiliar words to avoid guessing.",
  "Rhythm in typing is as important as raw speed.",
  "Typing silently can be a sign of light key presses.",
  "With time, your fingers will fly across the keys.",
  "You can hit new records by staying consistent.",
  "Today's small effort brings tomorrow's big result.",
  "High accuracy is a form of respect for the text.",
  "Typing clearly helps others read your work faster.",
  "Build the habit of finishing each practice round.",
  "Move past frustration and keep improving step by step.",
  "Over time, your baseline speed will keep rising.",
  "Strong typing skills make digital life smoother.",
  "Believe that you can become a very fast typist.",
  "Stay curious about how fast you might eventually go.",
  "This sentence is another chance to train your hands.",
  "Notice how fewer errors feel satisfying and calm.",
  "Your accuracy and speed are improving with every line.",
  "The more you practice, the more natural typing feels.",
  "Right now is a great time to sharpen your skills."
];
